version: '3'

services:
  backend:
    build: ./
    container_name: aba_api
    environment:
      - PORT=500
      - PORT=5000
      - MONGODB_URI=mongodb://localhost:27017/aba
      - EMAIL_SERVICE_URL_V1=https://telvida-email.onrender.com/api/v1
      - JWT_SECRET=yJG2CVYcuceuMXopLLkaBpUnajO9Zw3hz0o6Z6t96unSsfCdST9ZjYpiJ1YoJmcFFXpVIVAyEBi9NsjbqzLSr7kAn43HAcRIPSbeLyIxjpIQDDw6hhie2MMZinGENXASD6ghSKXZE2vQk4LmODglTu
      - REFRESH_JWT_SECRET=857WdqLyCOQOmelFvtJtPWOkJifyVY3ohUZSGoqCXY32j64A27WcUJsIU2eCQ0apmYRHtE7c4Pm2DW2sosWF1mNDakw0EzJ8aWOdFqDdv1OrSOa1xeiGlwCZE4UfRnmJ5EkuQ6kX6COQ
      - JWT_AUTH_TOKEN_EXPIRATION=45d
      - JWT_REFRESH_TOKEN_EXPIRATION=120d
      - RABBIT_MQ_URI=amqp://guest:guest@127.0.0.1:5672
      - RABBIT_MQ_ABA_QUEUE=ABA
    ports:
      - '5000:5000'
    depends_on:
      - database
    networks:
      - nestjs_network

  database:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - "./mongodb-backup:/data/db"
    networks:
      - nestjs_network

networks:
  nestjs_network:
    driver: bridge
