export const appInfo = {
    appName: 'ABA',
    appEmail: 'aba@telvida.com',
    companyName: 'ABA LLC',
    companyPhone: '+234-8138-234-786'
}
export const errors = {
    AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
    FORBIDDEN_ERROR: 'ACCESS_DENIED_ERROR',
    NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
    DATA_CONFLICT_ERROR: 'DATA_CONFLICT_ERROR',
    NOT_ACCEPTABLE_ERROR: 'NOT_ACCEPTABLE_ERROR',
    UNPROCESSABLE_DATA_ERROR: 'UNPROCESSABLE_DATA_ERROR',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
}