export const events = {
  SUPPORT_CREATED: 'SUPPORT_CREATED',
  SUPPORT_UPDATED: 'SUPPORT_UPDATED',
  SUPPORT_STATUS_CHANGED: 'SUPPORT_STATUS_CHANGED',
  SUPPORT_STATUS_CLOSED: 'SUPPORT_STATUS_CLOSED',
}

