export const events = {
  SUPPORT_CREATED: 'SUPPORT_CREATED',
  SUPPORT_UPDATED: 'SUPPORT_UPDATED',
  SUPPORT_STATUS_CHANGED: 'SUPPORT_STATUS_CHANGED',
  SUPPORT_STATUS_CLOSED: 'SUPPORT_STATUS_CLOSED',

  USER_CREATED: 'USER_CREATED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  VERIFICATION_TOKEN_REQUEST: 'VERIFICATION_TOKEN_REQUEST',
  ACCOUNT_VERIFIED: 'ACCOUNT_VERIFIED',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',

  FRIENDSHIP_INVITATION_CREATED: 'FRIENDSHIP_INVITATION_CREATED',
  FRIENDSHIP_INVITATION_ACCEPTED: 'FRIENDSHIP_INVITATION_ACCEPTED',
  FRIENDSHIP_INVITATION_DECLINED: 'FRIENDSHIP_INVITATION_DECLINED',

  FRIENDSHIP_CREATED: 'FRIENDSHIP_CREATED',
  FRIENDSHIP_DELETED: 'FRIENDSHIP_DELETED',

  CONVERSATION_CREATED: 'CONVERSATION_CREATED',
  FETCH_CONVERSATIONS: 'FETCH_CONVERSATIONS',
  CONVERSATION_DELETED: 'CONVERSATION_DELETED',
};

export const allowedFileTypes = [
  '.jpeg',
  '.jpg',
  '.png',
  '.gif',
  '.pdf',
  '.docx',
  '.xls',
  '.xlsx',
  '.ppt',
  '.pptx',
  '.txt',
  '.gif',
  '.zip',
  '.doc',
  '.mp3',
  '.wav',
  '.mp4',
  '.avi',
  '.mov',
  '.wmv',
  '.csv',
  '.webp',
];

export const maxFileSize = 100000000; // 100MB in bytes
