export const events = {
  SUPPORT_CREATED: 'SUPPORT_CREATED',
  SUPPORT_UPDATED: 'SUPPORT_UPDATED',
  SUPPORT_STATUS_CHANGED: 'SUPPORT_STATUS_CHANGED',
  SUPPORT_STATUS_CLOSED: 'SUPPORT_STATUS_CLOSED',

  USER_CREATED: 'USER_CREATED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  VERIFICATION_TOKEN_REQUEST: 'VERIFICATION_TOKEN_REQUEST',
  ACCOUNT_VERIFIED: 'ACCOUNT_VERIFIED',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED'
}

